SemaNewsWeb/Controllers/ArticleStructureController.cs
using SemaNewsCore.Models;
using SemaNewsWeb.ViewModels;
using SemaNews.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SemaNewsWeb.Controllers
{
    public class ArticleStructureController : Controller
    {
        private SemaNewsDBContext entities = new SemaNewsDBContext();

        public ActionResult Create(int newspaperId, string articleUrl)
        {
            var newspaper = entities.Newspapers.Find(newspaperId);

            var htmlDocument = SemaNews.Utilities.HtmlHandler.GetHtmlSource(articleUrl);
            foreach (var item in htmlDocument.DocumentNode.Descendants("base"))
                item.RemoveAll();
            ViewBag.htmlDocumentStr = htmlDocument.DocumentNode.OuterHtml;
            ViewBag.newspaperId = newspaperId;

            ArticleStructure aStruct = ArticleStructure.GetArticleStructure(newspaperId, 0);

            return View(aStruct);
        }

        [HttpPost]
        public ActionResult Create(ArticleStructure aStruct)
        {
            try
            {
                var newspaper = entities.Newspapers.Find(aStruct.Newspaper.Id);
                var maxGroupElement = newspaper.ArticleWebElements.OrderBy(x => x.Group).LastOrDefault(); ;
                int group = maxGroupElement == null ? 1 : (int)maxGroupElement.Group + 1;
                aStruct.GroupIdentity = group;
                // TODO: Add insert logic here
                if (aStruct.AddToDB(entities))
                    return RedirectToAction("ManageArticleStructures", "Newspaper", new { id = aStruct.Newspaper.Id });
                else
                    return View();
            }
            catch
            {
                return View();
            }
        }

        [HttpPost]
        public ActionResult Delete(int groupId, int newspaperId)
        {
            var newspaper = entities.Newspapers.Find(newspaperId);
            var delGroup = newspaper.ArticleWebElements.Where(x => x.Group == groupId);
            entities.ArticleWebElements.RemoveRange(delGroup);
            entities.SaveChanges();
            return RedirectToAction("ManageArticleStructures", "Newspaper", new { id = newspaper.Id });
        }
    }
}

SemaNewsWeb/Views/ArticleStructure/Create.cshtml
@model SemaNewsCore.Models.ArticleStructure
@{
    Layout = null;
}

@Html.Raw(ViewBag.htmlDocumentStr)

<!-- STRUCT MANAGE AREA -->

<!-- HEAD -->
<link rel="stylesheet" href="~/Content/DefineStruct.css" />
<script type="text/javascript" src="http://code.jquery.com/jquery-1.7.1.js"></script>
<script type="text/javascript" src="~/Scripts/Custom/DefineStruct.js"></script>
<!-- END HEAD -->

<!-- BODY -->
<!-- Define field popup -->
<div id="article-define-str-popup" class="WMDefineForm CommonCss">
    <div class="modal-header"> 
        <button aria-hidden="true" data-dismiss="modal" class="close" onclick="CloseDefineForm()" type="button">×</button>
        <h3>Định nghĩa cấu trúc trang tin bài</h3>
    </div>
    @using (Html.BeginForm("Create","ArticleStructure", FormMethod.Post)) {
        <div class="modal-body">
            <table>
                @Html.HiddenFor(model=>model.Newspaper.Id)
                @Html.EditorFor(model=>model.TitleElement, new { label = "Tiêu đề" })
                @Html.EditorFor(model=>model.AbstractElement, new { label = "Tóm tắt" })
                @Html.EditorFor(model=>model.DatePostedElement, new { label = "Thời gian đăng tải" })
                @Html.EditorFor(model=>model.ContentElement, new { label = "Nội dung" })
                @Html.EditorFor(model=>model.AuthorElement, new { label = "Tác giả" })
                @Html.EditorFor(model=>model.TagElement, new { label = "Các từ khóa" })
                @Html.EditorFor(model=>model.PaginationElement, new { label = "Phân trang" })
            </table>
        </div>
        <div class="modal-footer">

             <input type="submit" class="btn" value="Lưu" style="text-align:center" />
        </div>
    }
</div>
<!-- End Define field popup -->


<div id="WMController" class="WMController CommonCss">
    <div id="WMCreateForm">
   		<input type="button" id="WMbtnHoverMode" class="btn" onclick="ActiveHover()" value="Bắt đầu chọn"/>
   		<input type="text" id="WMtxtXpath" class="btn"  placeholder="xpath" />
        <input type="button" id="WMbtnParentEle" class="btn" onclick="ParentSelect()" value="Element chat"/>
        <input type="button" id="WMbtnChildEle" class="btn" onclick="FirstChildSelect()" value="Element con"/>
        <input type="button" id="WMbtnPrevSibling" class="btn" onclick="PreviousSiblingSelect()" value="Đồng cấp trước"/>
        <input type="button" id="WMbtnNextSibling" class="btn" onclick="NextSiblingSelect()" value="Đồng cấp tiếp theo"/>

        <br />
             
        <input type="button" id="article-add-element-btn" class="btn" value="Thêm Element"/>
        <input type="button" id="article-struct-form-btn" class="btn" value="Bảng định nghĩa" onclick="ActiveDefineForm()"/>
        <a class="btn btn-inverse" href="#" style="float:right">Quay lại</a>
        <div id="WMConfirmInputValue" style="color:#FFF; display:none;">Đã lưu vào "bảng định nghĩa" !!!</div>

    </div>         
</div>

<script>
    $(document).ready(function () {
        setTimeout(function () {
            $('#article-define-str-popup').show();
        }, 500);
    });
</script>