SemaNewsWeb/Controllers/NewsController.cs
using SemaNewsCore.Models;
using SemaNewsWeb.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;

namespace SemaNewsWeb.Controllers
{
    public class NewsController : Controller
    {
        SemaNewsDBContext entities = new SemaNewsDBContext();

        public ActionResult Index()
        {
            var rootGFs = entities.GetRootGFiels().OrderBy(m => m.Name).ToList();
            return View(rootGFs);
        }

        public ActionResult Category(int id, int? page, int? size)
        {
            var gfield = entities.GFields.Find(id);
            List<MsgNotification> Messages = new List<MsgNotification>();

            var pageNumber = page ?? 1;
            var pageSize = size ?? 10;

            if (gfield == null)
            {
                Messages.Add(new MsgNotification("LỖI! Lĩnh vực yêu cầu không tồn tại", MsgType.Error));
                ViewBag.Messages = Messages;
                ViewBag.Title = "Lỗi!";
                return View();
            
            }

            var articles = gfield.GetArticles(entities, true, true);
            if (gfield.Name == "Tỉnh Bình Dương")
            {
                var allArticles = entities.Articles.ToList();

                articles = allArticles.Where(m => m.IsRelevantToLocal == true).ToList();
            }

            var results = articles.OrderByDescending(m=>m.CollectedDate).ToPagedList(pageNumber, pageSize);

            var catergoryDetailsVM = new CategoryDetailsVM()
            {
                GField = gfield,
                Articles = results,
                Ancestors = GField.GetAncestors(id),
            };

            ViewBag.Title = gfield.Name;
            ViewBag.PageNumber = results.PageNumber;
            ViewBag.PageSize = results.PageSize;
            ViewBag.PageCount = results.PageCount;

            return View(catergoryDetailsVM);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                entities.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SemaNewsWeb/Controllers/TopicController.cs
using SemaNewsCore.Models;
using SemaNewsWeb.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SemaNewsWeb.Controllers
{
    [Authorize]
    public class TopicController : Controller
    {
        //
        // GET: /Topic/
        SemaNewsDBContext entities = new SemaNewsDBContext();
        public ActionResult Index(string filter = "")
        {
            if (string.IsNullOrEmpty(filter) == false)
            {
                ViewBag.FilterSting = filter;
                return View(entities.Topics.Where(m => m.Name.ToLower().Contains(filter.ToLower())).ToList());
            }

            return View(entities.Topics);
        }

        public ActionResult Create()
        {
            var LDVL_Keyphrases = new string[] { };
            var DT_Keyphrases = new string[] { };
            try
            {
                LDVL_Keyphrases = SearchLibrary.Helper.KeyphraseUtility.GetKeyphraseFromDatabase().Select(m => m.Name).ToArray();
                DT_Keyphrases = SearchLibrary.Helper.KeyphraseUtility.GetKeyphraseFromDatabase_DTCDTNN().Select(m => m.Name).ToArray();
            }
            catch
            {
            }
            ViewData["LDVL_Keyphrases"] = LDVL_Keyphrases;
            ViewData["DT_Keyphrases"] = DT_Keyphrases;

            return View(new TopicVM()); 
        }

        [HttpPost]
        public ActionResult AjaxCreate(TopicVM topic)
        {
            var newTopic = topic.ParseToTopic();
            var isValid = true;
            if (isValid)
            {
                entities.Topics.Add(newTopic);
                entities.SaveChanges();
                return Json(new { OK = true, Message = string.Format("Đã thêm chủ đề {0} thành công", newTopic.Name) });
            }
            return Json(new { OK = false, Message = "Đã có lỗi xảy ra trong quá trình thực hiện yêu cầu" });
        }

        public ActionResult Edit(int id)
        {
            var LDVL_Keyphrases = new string[] { };
            var DT_Keyphrases = new string[] { };
            try
            {
                LDVL_Keyphrases = SearchLibrary.Helper.KeyphraseUtility.GetKeyphraseFromDatabase().Select(m => m.Name).ToArray();
                DT_Keyphrases = SearchLibrary.Helper.KeyphraseUtility.GetKeyphraseFromDatabase_DTCDTNN().Select(m => m.Name).ToArray();
            }
            catch
            {
            }
            ViewData["LDVL_Keyphrases"] = LDVL_Keyphrases;
            ViewData["DT_Keyphrases"] = DT_Keyphrases;

            var topic = entities.Topics.Find(id);
            var topicVM = new TopicVM(topic);

            return View(topicVM);
        }

        [HttpPost]
        public ActionResult AjaxEdit(TopicVM topic)
        {
            var errorResult = Json(new { OK = false, Message = string.Format("Đã có lỗi xảy ra trong quá trình thực hiện yêu cầu")});
            try
            {
                if (topic.Topic != null && topic.Topic.Id != 0)
                {
                    var targetTopic = entities.Topics.Find(topic.Topic.Id);
                    if (targetTopic == null)
                        return errorResult;

                    var temp = topic.ParseToTopic();
                    targetTopic.Name = temp.Name;
                    targetTopic.Description = temp.Description;
                    targetTopic.Tags = temp.Tags;
                    targetTopic.Keyphrases = temp.Keyphrases;
                    //Initialize graphs

                    //

                    entities.Entry(targetTopic).State = System.Data.Entity.EntityState.Modified;
                    entities.SaveChanges();

                    return Json(new { OK = true, Message = string.Format("Thay đổi thông tin chủ đề \"{0}\" thành công", targetTopic.Name), Data = topic });
                }
                 
                return errorResult;      
            }
            catch
            {
                return errorResult;
            }
        }

        [HttpPost]
        public ActionResult AjaxDelete(int id)
        {
            var errorResult = Json(new { OK = false, Message = string.Format("Đã có lỗi xảy ra trong quá trình thực hiện yêu cầu") });
            var delTopic = entities.Topics.Find(id);
            if (delTopic == null)
            {
                return errorResult;
            }

            try
            {
                if (ModelState.IsValid)
                {
                    entities.Topics.Remove(delTopic);
                    entities.Entry(delTopic).State = System.Data.Entity.EntityState.Deleted;

                    entities.SaveChanges();
                    return Json(new { OK = true, Message = string.Format("Chủ đề \"{0}\" đã được xóa thành công", delTopic.Name), Data = delTopic });
                }
                return errorResult;
            }
            catch
            {
                return errorResult;
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                entities.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SemaNewsWeb/Views/Shared/_AdminPartial.cshtml
@if (Request.IsAuthenticated && User.IsInRole("Administrator"))
{
    <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#"><span class="fa fa-gears"></span>  Quản lí <b class="caret"></b></a>
        <ul class="dropdown-menu">
            <li><a href="@Url.Action("Index", "Newspaper")"><span class="fa fa-database"></span> Cấu trúc các trang báo</a></li>
            <li><a href="@Url.Action("Set","Article")"><span class="fa fa-database"></span> Kho tin bài</a></li>
            <li><a href="@Url.Action("Config", "Category")"><span class="fa fa-folder"></span> Lĩnh vực phân loại tin bài</a></li>
            <li><a href="@Url.Action("Index", "Topic")"><span class="fa fa-book"></span> Chủ đề tin tức</a></li>
            <li><a href="@Url.Action("Index", "Collector")"><span class="fa fa-download"></span> Bộ thu thập tin tức</a></li>
        </ul>
    </li>
}

SemaNewsWeb/Views/Shared/_EmptyLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>SemaNews- @ViewBag.Title</title>

    <!-- Latest compiled and minified CSS -->
    @RenderSection("siteHeader", required: false)
</head>
<body role="document">
    @RenderSection("siteBody", required: false)
    @RenderSection("tools", required: false)
    @RenderBody()
    @RenderSection("scripts", required: false)
</body>
</html>

SemaNewsWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>SemaNews - @ViewBag.Title</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />

    <link rel="stylesheet" href="~/Content/FontAwesome/css/font-awesome.min.css" />
    <link rel="stylesheet" href="~/Content/Bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/Content/Bootstrap/css/carousel.css" />
    <link rel="stylesheet" href="~/Content/MagicSuggest/magicsuggest-min.css">
    <link rel="stylesheet" href="~/Content/Switcher/style-switcher.css" />
    <link rel="stylesheet" href="~/Content/TreeviewBootstrap/bootstrap-treeview.css" />
    <link rel="stylesheet" href="~/Content/Site.css" />
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div id="main-navbar" class="navbar navbar-default navbar-fixed-top mirror-background" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="~/">SemaNews</a>
            </div>
            <div class="navbar-collapse in" style="height: auto;">
                <ul class="nav navbar-nav">
                    <li><a href="~/">Trang chủ</a></li>
                    @Html.Partial("_AdminPartial")
                    <li class="drop-down">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Tin tức <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li class="dropdown-submenu">
                                <a href="#">Điểm tin</a>
                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="@Url.Action("Index", "Highlights")">Tin chung</a>
                                    </li>
                                    <li>
                                        <a href="@Url.Action("Index", "Highlights", new { @isRelevantToLocalOnly = true })">Tin tỉnh Bình Dương</a>
                                    </li>
                                </ul>
                            </li>
                            <li class="dropdown-submenu">
                                <a href="@Url.Action("Index","News")">Tin tổng hợp</a>
                                <ul class="dropdown-menu">
                                    @Html.Raw(SemaNewsWeb.Helpers.CategoryTreeBuilder.BuildGFTree())
                                </ul>
                            </li>
                        </ul>
                    </li>
                    <li><a href="#about">Giới thiệu</a></li>
                </ul>
                @Html.Partial("_LoginPartial")

            </div>
            <!--/.nav-collapse -->
        </div>
    </div>

    @RenderBody()

    @RenderSection("featured", false)

    <!-- /container -->
    <footer id="footer-white" class="ui-light">
        <div class="container">
            <div class="row">
                <div class="col-sm-6 menu">
                    <h3>INFO</h3>
                    <ul>
                        <li>
                            <a href="#">University of Information Technology</a>
                        </li>
                        <li>
                            <a href="http://ke-app.sytes.net">KE Group</a>
                        </li>
                        <li>
                            <a href="blog.html">Coming soon</a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="row credits">
                <div class="col-md-12 text-center">
                    <p>Copyright © 2014. SemaNews</p>
                </div>
            </div>
        </div>
    </footer>
    @*@Scripts.Render("~/bundles/jquery")*@
    @*@Scripts.Render("~/bundles/bootstrapjs")*@
    <script src="~/Scripts/jquery.js"></script>
    <script src="~/Scripts/jquery-1.9.1.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Content/Bootstrap/js/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery.bootstrap-growl.min.js"></script>
    <script src="~/Content/MagicSuggest/magicsuggest-min.js"></script>
    <script src="~/Content/TreeviewBootstrap/bootstrap-treeview.js"></script>
    <script src="~/Scripts/Custom/semanews-common.js"></script>
    <script src="~/Content/Switcher/js-switcher.js"></script>

    <!--Handling notification messages-->
    <script>
        $(document).ready(function(){
            $(function () {
                $("[data-tooggle='tooltip']").tooltip();
            });

            var messages = @Html.Raw(Newtonsoft.Json.JsonConvert.SerializeObject(ViewBag.Messages));
            if(messages !=null && messages.length!=0)
            {
                for(var i = 0; i<messages.length; i++)
                {
                    notifyMessage(messages[i].MessageContent, messages[i].MessageType);
                }
            }
            
        });
    </script>
    @RenderSection("scripts", required: false)
</body>
</html>

SemaNewsWeb/Views/Shared/_SimpleLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>SemaNews- @ViewBag.Title</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="~/Content/Bootstrap/css/bootstrap.min.css">

    @Styles.Render("~/Content/Site.css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body role="document">
    <div class="container">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    <script src="~/Content/assets/js/jquery-1.10.2.min.js"></script>
    <script src="~/Content/js/bootstrap.min.js"></script>
    <script src="~/Content/assets/js/docs.min.js"></script>

    @RenderSection("scripts", required: false)
</body>
</html>